import type { SearchApiResponse } from '../types/internship';

export const FALLBACK_INTERNSHIPS: SearchApiResponse = {
  internships_meta: {
    "65532": {
      "id": 65532,
      "title": "Data Science Intern",
      "employment_type": "internship",
      "company_name": "Google",
      "company_url": "/company/google",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Bhavya",
      "company_logo": "google.png",
      "type": "regular",
      "url": "data-science-internship-at-google",
      "is_active": true,
      "expires_at": "2026-06-30",
      "closed_at": "",
      "profile_name": "Data Science",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "3 Months",
      "stipend": {
        "salary": "₹ 50,000 /month",
        "tooltip": null,
        "salaryValue1": 50000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "Today",
      "postedOnDateTime": 1704825000,
      "application_deadline": "30 Jun' 26",
      "expiring_in": "Apply by 30 Jun",
      "posted_by_label": "Today",
      "posted_by_label_type": "success",
      "location_names": ["Munnar", "Delhi", "Lucknow", "Tarn Taran"],
      "locations": [
        { "string": "Munnar", "link": "Munnar", "country": "India", "region": "Idukki", "locationName": "Munnar" },
        { "string": "Delhi", "link": "Delhi", "country": "India", "region": null, "locationName": "Delhi" },
        { "string": "Lucknow", "link": "Lucknow", "country": "India", "region": "Lucknow", "locationName": "Lucknow" }
      ],
      "is_ppo": false,
      "ppo_label_value": "With job offer",
      "office_days": null
    },
    "65533": {
      "id": 65533,
      "title": "Frontend Web Developer Intern",
      "employment_type": "internship",
      "company_name": "Meta",
      "company_url": "/company/meta",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Alok",
      "company_logo": "meta.png",
      "type": "regular",
      "url": "frontend-developer-internship-at-meta",
      "is_active": true,
      "expires_at": "2026-07-15",
      "closed_at": "",
      "profile_name": "Frontend Development",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "6 Months",
      "stipend": {
        "salary": "₹ 45,000 /month",
        "tooltip": null,
        "salaryValue1": 45000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "Yesterday",
      "postedOnDateTime": 1704738600,
      "application_deadline": "15 Jul' 26",
      "expiring_in": "Apply by 15 Jul",
      "posted_by_label": "1 day ago",
      "posted_by_label_type": "info",
      "location_names": ["Mumbai", "Bangalore", "Work from Home"],
      "locations": [
        { "string": "Mumbai", "link": "Mumbai", "country": "India", "region": "Maharashtra", "locationName": "Mumbai" },
        { "string": "Bangalore", "link": "Bangalore", "country": "India", "region": "Karnataka", "locationName": "Bangalore" }
      ],
      "is_ppo": true,
      "ppo_label_value": "Job offer",
      "office_days": null
    },
    "65534": {
      "id": 65534,
      "title": "Mobile App Developer Intern",
      "employment_type": "internship",
      "company_name": "Apple",
      "company_url": "/company/apple",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Siddharth",
      "company_logo": "apple.png",
      "type": "regular",
      "url": "ios-developer-internship-at-apple",
      "is_active": true,
      "expires_at": "2026-06-25",
      "closed_at": "",
      "profile_name": "Mobile App Development",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "3 Months",
      "stipend": {
        "salary": "₹ 60,000 /month",
        "tooltip": null,
        "salaryValue1": 60000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "2 days ago",
      "postedOnDateTime": 1704652200,
      "application_deadline": "25 Jun' 26",
      "expiring_in": "Apply by 25 Jun",
      "posted_by_label": "2 days ago",
      "posted_by_label_type": "info",
      "location_names": ["Hyderabad", "Work from Home"],
      "locations": [
        { "string": "Hyderabad", "link": "Hyderabad", "country": "India", "region": "Telangana", "locationName": "Hyderabad" }
      ],
      "is_ppo": false,
      "ppo_label_value": "With job offer",
      "office_days": null
    },
    "65535": {
      "id": 65535,
      "title": "Marketing Associate Intern",
      "employment_type": "internship",
      "company_name": "Netflix",
      "company_url": "/company/netflix",
      "is_premium": false,
      "is_premium_internship": false,
      "employer_name": "Monica",
      "company_logo": "netflix.png",
      "type": "regular",
      "url": "marketing-internship-at-netflix",
      "is_active": true,
      "expires_at": "2026-06-20",
      "closed_at": "",
      "profile_name": "Marketing",
      "part_time": true,
      "start_date": "Starts Immediately",
      "duration": "2 Months",
      "stipend": {
        "salary": "₹ 15,000 /month",
        "tooltip": null,
        "salaryValue1": 15000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "3 days ago",
      "postedOnDateTime": 1704565800,
      "application_deadline": "20 Jun' 26",
      "expiring_in": "Apply by 20 Jun",
      "posted_by_label": "3 days ago",
      "posted_by_label_type": "info",
      "location_names": ["Delhi", "Mumbai"],
      "locations": [
        { "string": "Delhi", "link": "Delhi", "country": "India", "region": null, "locationName": "Delhi" },
        { "string": "Mumbai", "link": "Mumbai", "country": "India", "region": "Maharashtra", "locationName": "Mumbai" }
      ],
      "is_ppo": true,
      "ppo_label_value": "Job offer potential",
      "office_days": null
    },
    "65536": {
      "id": 65536,
      "title": "Backend Development Intern",
      "employment_type": "internship",
      "company_name": "Amazon",
      "company_url": "/company/amazon",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Rohit",
      "company_logo": "amazon.png",
      "type": "regular",
      "url": "backend-development-internship-at-amazon",
      "is_active": true,
      "expires_at": "2026-07-01",
      "closed_at": "",
      "profile_name": "Backend Development",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "6 Months",
      "stipend": {
        "salary": "₹ 40,000 /month",
        "tooltip": null,
        "salaryValue1": 40000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "4 days ago",
      "postedOnDateTime": 1704479400,
      "application_deadline": "01 Jul' 26",
      "expiring_in": "Apply by 01 Jul",
      "posted_by_label": "4 days ago",
      "posted_by_label_type": "info",
      "location_names": ["Bangalore", "Chennai"],
      "locations": [
        { "string": "Bangalore", "link": "Bangalore", "country": "India", "region": "Karnataka", "locationName": "Bangalore" },
        { "string": "Chennai", "link": "Chennai", "country": "India", "region": "Tamil Nadu", "locationName": "Chennai" }
      ],
      "is_ppo": true,
      "ppo_label_value": "Job offer",
      "office_days": null
    },
    "65537": {
      "id": 65537,
      "title": "Product Management Intern",
      "employment_type": "internship",
      "company_name": "Microsoft",
      "company_url": "/company/microsoft",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Riya",
      "company_logo": "microsoft.png",
      "type": "regular",
      "url": "product-management-internship-at-microsoft",
      "is_active": true,
      "expires_at": "2026-06-18",
      "closed_at": "",
      "profile_name": "Product Management",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "3 Months",
      "stipend": {
        "salary": "₹ 35,000 /month",
        "tooltip": null,
        "salaryValue1": 35000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "5 days ago",
      "postedOnDateTime": 1704393000,
      "application_deadline": "18 Jun' 26",
      "expiring_in": "Apply by 18 Jun",
      "posted_by_label": "5 days ago",
      "posted_by_label_type": "info",
      "location_names": ["Hyderabad", "Noida"],
      "locations": [
        { "string": "Hyderabad", "link": "Hyderabad", "country": "India", "region": "Telangana", "locationName": "Hyderabad" },
        { "string": "Noida", "link": "Noida", "country": "India", "region": "Uttar Pradesh", "locationName": "Noida" }
      ],
      "is_ppo": false,
      "ppo_label_value": "",
      "office_days": null
    },
    "65538": {
      "id": 65538,
      "title": "Graphic Design Intern",
      "employment_type": "internship",
      "company_name": "Canva",
      "company_url": "/company/canva",
      "is_premium": false,
      "is_premium_internship": false,
      "employer_name": "Sarah",
      "company_logo": "canva.png",
      "type": "regular",
      "url": "graphic-design-internship-at-canva",
      "is_active": true,
      "expires_at": "2026-06-15",
      "closed_at": "",
      "profile_name": "Graphic Design",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "1 Month",
      "stipend": {
        "salary": "₹ 8,000 /month",
        "tooltip": null,
        "salaryValue1": 8000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "6 days ago",
      "postedOnDateTime": 1704306600,
      "application_deadline": "15 Jun' 26",
      "expiring_in": "Apply by 15 Jun",
      "posted_by_label": "6 days ago",
      "posted_by_label_type": "info",
      "location_names": ["Pune", "Work from Home"],
      "locations": [
        { "string": "Pune", "link": "Pune", "country": "India", "region": "Maharashtra", "locationName": "Pune" }
      ],
      "is_ppo": false,
      "ppo_label_value": "",
      "office_days": null
    },
    "65539": {
      "id": 65539,
      "title": "Cybersecurity Analyst Intern",
      "employment_type": "internship",
      "company_name": "Cloudflare",
      "company_url": "/company/cloudflare",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "David",
      "company_logo": "cloudflare.png",
      "type": "regular",
      "url": "cybersecurity-internship-at-cloudflare",
      "is_active": true,
      "expires_at": "2026-06-22",
      "closed_at": "",
      "profile_name": "Cyber Security",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "4 Months",
      "stipend": {
        "salary": "₹ 30,000 /month",
        "tooltip": null,
        "salaryValue1": 30000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "1 week ago",
      "postedOnDateTime": 1704220200,
      "application_deadline": "22 Jun' 26",
      "expiring_in": "Apply by 22 Jun",
      "posted_by_label": "1 week ago",
      "posted_by_label_type": "info",
      "location_names": ["Bangalore", "Work from Home"],
      "locations": [
        { "string": "Bangalore", "link": "Bangalore", "country": "India", "region": "Karnataka", "locationName": "Bangalore" }
      ],
      "is_ppo": true,
      "ppo_label_value": "Job offer",
      "office_days": null
    },
    "65540": {
      "id": 65540,
      "title": "UI/UX Designer Intern",
      "employment_type": "internship",
      "company_name": "Figma",
      "company_url": "/company/figma",
      "is_premium": true,
      "is_premium_internship": true,
      "employer_name": "Sophie",
      "company_logo": "figma.png",
      "type": "regular",
      "url": "uiux-design-internship-at-figma",
      "is_active": true,
      "expires_at": "2026-06-28",
      "closed_at": "",
      "profile_name": "UI/UX Design",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "3 Months",
      "stipend": {
        "salary": "₹ 25,000 /month",
        "tooltip": null,
        "salaryValue1": 25000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "1 week ago",
      "postedOnDateTime": 1704220200,
      "application_deadline": "28 Jun' 26",
      "expiring_in": "Apply by 28 Jun",
      "posted_by_label": "1 week ago",
      "posted_by_label_type": "info",
      "location_names": ["Delhi", "Work from Home"],
      "locations": [
        { "string": "Delhi", "link": "Delhi", "country": "India", "region": null, "locationName": "Delhi" }
      ],
      "is_ppo": false,
      "ppo_label_value": "",
      "office_days": null
    },
    "65541": {
      "id": 65541,
      "title": "DevOps Engineer Intern",
      "employment_type": "internship",
      "company_name": "RedHat",
      "company_url": "/company/redhat",
      "is_premium": false,
      "is_premium_internship": false,
      "employer_name": "Marcus",
      "company_logo": "redhat.png",
      "type": "regular",
      "url": "devops-internship-at-redhat",
      "is_active": true,
      "expires_at": "2026-07-10",
      "closed_at": "",
      "profile_name": "DevOps",
      "part_time": false,
      "start_date": "Starts Immediately",
      "duration": "6 Months",
      "stipend": {
        "salary": "₹ 32,000 /month",
        "tooltip": null,
        "salaryValue1": 32000,
        "salaryValue2": null,
        "salaryType": "fixed",
        "currency": "INR ",
        "scale": "permonth",
        "large_stipend_text": false
      },
      "salary": null,
      "experience": "",
      "posted_on": "2 weeks ago",
      "postedOnDateTime": 1703615400,
      "application_deadline": "10 Jul' 26",
      "expiring_in": "Apply by 10 Jul",
      "posted_by_label": "2 weeks ago",
      "posted_by_label_type": "info",
      "location_names": ["Work from Home"],
      "locations": [],
      "is_ppo": true,
      "ppo_label_value": "Job offer",
      "office_days": null
    }
  },
  "internship_ids": [65532, 65533, 65534, 65535, 65536, 65537, 65538, 65539, 65540, 65541]
};
